import { InvoiceList } from './questoes';

export const invoceLists: InvoiceList[] = [
  {
    id:9860,
    Categoria: 'Ciências Humanas',
    Tag: 'Sociologia',
    Curso: '1ª SÉRIE / EM',
    Tipo: 'Aberta',
    Dificuldade: 'Difícil',
    status: 'Em moderação',
    completed: false,
    isSelected: false,
  },
  {
    id: 9861,
    Categoria: 'Filosofia',
    Tag: 'Aristóteles',
    Curso: '8° ANO EF',
    Tipo: 'Multipla Escolha',
    Dificuldade: 'Média',
    status: 'Aprovada',
    completed: false,
    isSelected: false,
  },
  {
    id: 9862,
    Categoria: 'Matemática',
    Tag: 'Álgebra',
    Curso: '2ª SÉRIE / EM',
    Tipo: 'Multipla Escolha',
    Dificuldade: 'Média',
    status: 'Aprovada',
    completed: false,
    isSelected: false,
  },
  {
    id: 9863,
    Categoria: 'Humanas',
    Tag: 'Guerra',
    Curso: '8° ANO EF',
    Dificuldade: 'Média',
    Tipo: 'Multipla Escolha',
    status: 'Em edição',
    completed: false,
    isSelected: false,
  },
  {
    id: 9864,
    Categoria: 'Filosofia',
    Tag: 'Platão',
    Curso: '1ª SÉRIE / EM',
    Tipo: 'Aberta',
    Dificuldade: 'Média',
    status: 'Em moderação',
    completed: false,
    isSelected: false,
  },
  {
    id: 9865,
    Categoria: 'Ciências',
    Tag: 'Guerra',
    Curso: '8° ANO EF',
    Tipo: 'Discursiva',
    Dificuldade: 'Média',
    status: 'Em edição',
    completed: false,
    isSelected: false,
  },
  {
    id: 9866,
    Categoria: 'Humanas',
    Tag: 'Guerra',
    Curso: '9° ANO EF',
    Tipo: 'Discursiva',
    Dificuldade: 'Fácil',
    status: 'Aprovada',
    completed: false,
    isSelected: false,
  },
  {
    id: 9867,
    Categoria: 'Matemática',
    Tag: 'Guerra',
    Curso: '9° ANO EF',
    Tipo: 'Discursiva',
    Dificuldade: 'Fácil',
    status: 'Aprovada',
    completed: false,
    isSelected: false,
  },
  {
    id: 9868,
    Categoria: 'Humanas',
    Tag: 'Guerra',
    Curso: '7° ANO EF',
    Tipo: 'Discursiva',
    Dificuldade: 'Média',
    status: 'Aprovada',
    completed: false,
    isSelected: false,
  },

  {
    id: 9869,
    Categoria: 'Geografia',
    Tag: 'Agricultura',
    Curso: '3ª SÉRIE / EM',
    Tipo: 'Discursiva',
    Dificuldade: 'Difícil',
    status: 'Em edição',
    completed: false,
    isSelected: false,
  },
  {
    id: 9870,
    Categoria: 'História',
    Tag: 'Ditadura',
    Curso: '3ª SÉRIE / EM',
    Tipo: 'Multipla Escolha',
    Dificuldade: 'Difícil',
    status: 'Em edição',
    completed: false,
    isSelected: false,
  },{
    id: 9870,
    Categoria: 'História',
    Tag: 'Ditadura',
    Curso: '3ª SÉRIE / EM',
    Tipo: 'Multipla Escolha',
    Dificuldade: 'Difícil',
    status: 'Em edição',
    completed: false,
    isSelected: false,
  },{
    id: 9870,
    Categoria: 'História',
    Tag: 'Ditadura',
    Curso: '3ª SÉRIE / EM',
    Tipo: 'Multipla Escolha',
    Dificuldade: 'Difícil',
    status: 'Em edição',
    completed: false,
    isSelected: false,
  },
  {
    id: 9870,
    Categoria: 'História',
    Tag: 'Ditadura',
    Curso: '3ª SÉRIE / EM',
    Tipo: 'Multipla Escolha',
    Dificuldade: 'Difícil',
    status: 'Em edição',
    completed: false,
    isSelected: false,
  },
  {
    id: 9870,
    Categoria: 'História',
    Tag: 'Ditadura',
    Curso: '3ª SÉRIE / EM',
    Tipo: 'Multipla Escolha',
    Dificuldade: 'Difícil',
    status: 'Em edição',
    completed: false,
    isSelected: false,
  }
  
];